name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx make

      - name: Build binaries
        run: |
            make build BUILD=release TARGET=${{ matrix.os }} ARCH=${{ matrix.arch }} VERSION=${GITHUB_REF_NAME}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .bin/watchforge-release-${{ matrix.os }}-${{ matrix.arch }}*